# -*- coding: utf-8 -*-
# Fichas novas 65–81 (mineração definitiva de 06/09/2026). Campos do template do catálogo.
# "Em quantos artigos aparece" e a lista de referências são gerados do JSON; aqui vai o texto dos demais campos.

NOVAS = {
65: dict(nome="Sensibilidade a hiperparâmetros de projeto do algoritmo (fora do uso da incerteza)", grupo="B",
  fontes="[MIN] 28 análises em 18 artigos (lista abaixo) · [PL-38] R2#9 (18/38; R1#12 'não recomendada') · [CAP4] tabela de hiperparâmetros (valores fixados nos artigos).",
  o_que="O efeito, sobre o endpoint (IGD/HV), de variar um hiperparâmetro do próprio algoritmo que NÃO define o uso da incerteza: tamanho de pool/ensemble (b14 Smax, c48 Q), nº de neurônios/profundidade (b4 H, c122 U/D, e7 J=K), frequência de retreino (b3 wmax, c122 Tmax), nº de gerações de busca no modelo (c241 gmax, e86 t_max), nº de pontos indutores (b15), fração de pareamento (c217 N/4), orçamento do solver interno (b9), η da seleção de subproblemas (e102), itertrain/iterr (e7), K de referência (b4).",
  dados="Nenhuma camada: exige reexecução com valores alternativos. A ⑤ (manifesto) registra apenas o valor efetivamente usado — insumo da tabela de valores, não da sensibilidade.",
  objetivo="No corpus: justificar os valores fixados ('confirms that our parameter setting is reasonable' — e102) e mostrar robustez ('relatively insensitive' — b3, c241). Na dissertação: nenhum (diretriz 1).",
  revela="Nos artigos: quase sempre saturação ou ótimo intermediário (b14 Smax=5/T=30; c48 Q=40; b4 K≈6; c241 gmax 10–50 'insensível'; e7 'sem orientação teórica para a taxa de dropout') e, com frequência, a escolha final feita por CUSTO e não por qualidade (c241 gmax=10 'to reduce computation time'; e7 J=K=40 'in consideration of the computational time').",
  como="Um parâmetro por vez, demais no valor padrão; 1–4 problemas 'representativos'; curvas de IGD × valor (média ou mediana de 20–30 execuções; c122 mediana de 21 nas últimas 100 avaliações; b15 5 sementes); raramente com teste (b15 Wilcoxon p<0,05 para K=3).",
  tecnicas="Varredura unidimensional (one-at-a-time); curvas de perfil; média±dp; ocasionalmente rank médio por valor (c241).",
  impl="Não implementável sob a diretriz (1). O que se implementa é a TABELA dos valores usados por algoritmo (⑤ manifesto + cap. 4), com a nota 'valores dos artigos de origem, sem varredura' — em 61.",
  estado="N — descartada como análise (diretriz 1); vira declaração em 61.",
  detalhes="Relação com 66 (o subconjunto de hiperparâmetros que define o USO da incerteza) e 45 (o que se pode medir sem reexecutar: acionamentos no ⑥). Nota de leitura: em 8 dos 18 artigos a sensibilidade está só no material suplementar (b3, e7, e103, e104, e86, e3, c267, c82) — o corpus a trata como obrigação editorial, não como resultado. Decisão que pede: como declarar no cap. 4/61 que os hiperparâmetros são os dos artigos."),

66: dict(nome="Sensibilidade ao parâmetro que governa o uso da incerteza (δ do gate, taxa de dropout, k da AUCB, β/ω do LCB) — nos artigos", grupo="B",
  fontes="[MIN] 3 análises diretas (b8 τ, e104 k/Nv/ωmax, e7 taxa de dropout) + os 15 blocos-roster 'parametros_do_uso_da_incerteza' (Anexo 8.6) · ficha 45 (a versão que a bateria pode fazer: contar acionamentos no ⑥) · [CAP4] tabela de parâmetros.",
  o_que="O efeito, sobre o endpoint, de variar o hiperparâmetro que define quanto/quando a incerteza entra na decisão: δ do K-RVEA (b3, fichas 45), δ da confiabilidade do PC-SAEA (c217), taxa de dropout da EDN (e7: 'no theoretic guidance… needs to be properly tuned'), k da AUCB (e104), φ/τ do KTA2 (b8), β do LCB (e64), ω do LB (mtm4), S/p da estimativa de entropia (c154), α/β do termo aleatório (c149).",
  dados="Sensibilidade fim-a-fim: nenhuma camada (exige reexecução). Tabela de valores: ⑤ (manifesto: sigma_dict, params) + artigos. Acionamentos sob o valor usado: ⑥ (ficha 45).",
  objetivo="Nos artigos: mostrar que o mecanismo é robusto ou escolher o valor. Na dissertação: documentar, para cada um dos 15, QUAL é o parâmetro que liga a incerteza à decisão e com que valor rodou — a legenda indispensável para ler 45, 52 e 36.",
  revela="Nos artigos: e7 admite que o parâmetro central do mecanismo não tem justificativa teórica; b3 relata que aumentar δ 'deteriora a diversidade' porque a incerteza é usada menos vezes; b8 escolhe φ=0,1N (o menor) 'por risco de indivíduos de incerteza muito alta prejudicarem a convergência'; c154 vê ganho nulo de S ou p maiores. Ou seja: a intensidade do uso da incerteza é ajustada empiricamente e, com frequência, para BAIXO.",
  como="Varredura do parâmetro em 1–4 problemas, IGD × valor; nos blocos-roster, a listagem nome = valor com localizador.",
  tecnicas="Varredura unidimensional; nos blocos-roster, catalogação (nome do parâmetro, papel, valor, onde está no artigo).",
  impl="Tabela 'parâmetros do uso da incerteza dos 15' a partir do Anexo 8.6 cruzada com ⑤ (valores efetivamente usados na bateria); 30 linhas; vai para o cap. 4 (apêndice) e serve de legenda a 45/52.",
  estado="N — a tabela é factível hoje; a sensibilidade fim-a-fim é descartada (diretriz 1).",
  detalhes="É a ficha que separa 'hiperparâmetro do algoritmo' (65) de 'hiperparâmetro da incerteza' — distinção que o cartão de extração pediu e que os agentes aplicaram (várias análises ficaram em 65 e não em 45 por isso). Relação: 45 (acionamentos), 52 (pares), 36 (por classe de medição). Decisão: onde publicar a tabela (cap. 4 × apêndice)."),

67: dict(nome="Ablação de componentes do próprio algoritmo que não são a incerteza (otimizador, seleção de subproblemas/lote, arquitetura do modelo)", grupo="B",
  fontes="[MIN] 21 análises em 14 artigos (lista abaixo) · [PL-38] R2#3 (26/38) · fichas 11/12/15 (ablação do σ) e 52.",
  o_que="A contribuição de um componente que não é o σ: otimizador híbrido IBEA/NSGA-II (b14), aprendizado da combinação da aquisição (b15 Static-EHVI), regiões de confiança/aquisição/reinicialização (c131), separação busca/gestão (c241 EMMOEA-IP), seleção de lote e otimizador interno (c261), arquitetura do classificador (c48), componentes da recompensa (c81), transferência (c82), seleção de subproblemas e ALCB (e102), motor de base (e103), indicador × aleatório (e104), EA interno (e16), dados extra/termo SBP (e40).",
  dados="Nenhuma camada: exige variantes executadas.",
  objetivo="Nos artigos: mostrar de onde vem o ganho declarado. Na dissertação: leitura literária — quanto do ganho dos métodos vem de componentes que NÃO são a incerteza.",
  revela="Resultados fracos ou negativos para a própria contribuição são comuns: e40 (termo SBP só melhora 9/48 e 'quase desaparece' em rc=10; 'highly tricky to measure the search bias'), c241 (expor toda a busca ao EI perde 8/11), c131 (GP global iguala em 2 de 3 problemas a custo 30 h × <1 h), c261 (submodular vs k-means é marginal), c48 (ensemble podado não é monotonicamente melhor), c82 (vantagem 'não universal'). Ver Anexo 8.3.",
  como="Variante com um componente removido/trocado, demais fixos; IGD/HV com Wilcoxon (+/=/−) ou média±EP; 3–16 problemas.",
  tecnicas="Ablação one-component-out; Wilcoxon rank-sum α=0,05 (b14, c241 Bonferroni, c261, e40 Holm); curvas (c131).",
  impl="Não implementável (diretriz 1). Uso: parágrafo do cap. 6 / 61 sobre o que a bateria não separa (o motor casado por D25 é o máximo de controle disponível: 9).",
  estado="N — descartada como análise.",
  detalhes="Diferença para 11/15: aqui ambas as variantes usam σ (o que muda não é a incerteza). Diferença para 68: aqui o tipo de surrogate é o mesmo. Relação: 9 (o casamento por motor é a nossa 'ablação' de motor), 51."),

68: dict(nome="Tipo de surrogate sob a mesma maquinaria (GP × NN × RBF × ensemble; independente × dependente; heterogêneo × homogêneo)", grupo="B",
  fontes="[MIN] 20 análises em 11 artigos (lista abaixo) · fichas 20 (taxonomia como variável) e 36 (sonda por classe de medição) · [CAP3] eixo surrogate (GP/RG/NN/CL).",
  o_que="O efeito de trocar o tipo de modelo mantendo o resto: BNN × GP por escala (c1: GP vence em 8D/poucos dados; BNN vence em 50D/1000 pontos), par-a-par × regressão × classificação (c217: 0/18/0 e 0/12/6, com tempos 1118 s × 1627 s × 245 s), heterogêneo × homogêneo (e3: HoE nunca vence), CoMOGP × GPs independentes (e102), GP dependente × independente (c106: 'little advantage' — negativo), LMC × independente (b15: LMC piora), Deep GP hetero × GP esparso × GP raso (b15), DNN × XGBoost por validação (b13), kernels por CV (c50), co-surrogate GP × polinomial (c82), arquiteturas por acurácia e correlação de erros (e8), surrogates por lote (c149).",
  dados="Nenhuma camada para a ablação. Entre algoritmos, ① + ③ dão a leitura confundida por classe de surrogate (20/36).",
  objetivo="Nos artigos: escolher/justificar o modelo. Na dissertação: contexto para ler o eixo surrogate da taxonomia com humildade (a bateria varia surrogate E motor E função ao mesmo tempo).",
  revela="Dois achados transversais úteis ao texto: (i) o regime (orçamento/dimensão) decide o modelo — c1 inverte o vencedor entre 8D e 50D; (ii) modelar correlação entre objetivos raramente compensa sob poucos dados — c106 e b15 negativos, c81 mede |ρ|<0,3 e assume independência (ficha 80).",
  como="Mesmo algoritmo com o modelo trocado; IGD/HV; às vezes só acurácia do modelo (b13, c50, e8).",
  tecnicas="Ablação de modelo; validação cruzada k-fold; comparação de MAE/RMSE por partição (treino/teste/extrapolação — e8).",
  impl="Não implementável como ablação. A leitura por eixo de surrogate (20) e a sonda por classe de medição (36) são as versões pós-hoc.",
  estado="N — descartada como análise; alimenta 20/36/61 e o cap. 6.",
  detalhes="Relação com 37 (agregação de m sigmas) e 80 (correlação entre objetivos). Nota: c217 reporta que 'o treino dos surrogates consome <10% do runtime' — dado de custo para 48."),

69: dict(nome="Custo da otimização da aquisição (tempo de busca) e complexidade assintótica por fase", grupo="F",
  fontes="[MIN] 15 análises em 13 artigos (lista abaixo) · ficha 48 (decomposição fit/busca/sonda) · [CD] ④ (`tempo_busca_s` por geração) · [CAP3/4] complexidades declaradas dos 15.",
  o_que="O custo do CRITÉRIO (não do modelo): tempo para otimizar/avaliar a aquisição por iteração e como cresce com D, M, |ND| e q — c100 (gradiente exato 10× mais rápido que diferenças finitas/CMA-ES), c154 (tempo de parede da aquisição cresce com S), c214/c222 (tempo de avaliar a aquisição em 100 candidatos; MESMO O(SK) × PESMO O(SKm³)), c238 (tempo de avaliar cada critério, 1000 repetições), c261 (Big-O por fase + CPU × q: 818 s × 9066 s em q=15), c262 (CBD × IEP: exponencial em q), emo1 (SMS-EGO O(|P*|^D)), e1 (nº de células da decomposição), c122 (CPU só entre os Python), e103/b14/jin3/c267 (Big-O por fase, sem medição).",
  dados="④ (`tempo_busca_s`, `tempo_fit_s`, `tempo_pred_sonda_s` por geração; `n_acumulado`); ⑤ (timing agregado); M (D por problema; família de aquisição por algoritmo).",
  objetivo="Separar, no custo do surrogate, o que é pagar pelo σ (ajuste do GP, O(n³): 46/48) do que é pagar pelo CRITÉRIO que usa o σ (busca da aquisição: informacionais e hipervolume pagam aqui).",
  revela="Se os métodos que usam a incerteza de forma mais elaborada (c154 JES, c262 qNEHVI, c238 EIM-h) são caros no ajuste ou na busca — e como isso cresce com D e com o tamanho do ND (c261/emo1: hipervolume explode com M e |P*|).",
  como="Por célula, somar `tempo_busca_s` e `tempo_fit_s` sobre gerações; razão busca/(busca+fit) por algoritmo e por família de aquisição (melhoria, hipervolume, informação, classificação); curvas de tempo_busca por geração × n_acumulado; tabela por D (3 níveis) e por M.",
  tecnicas="Agregação por célula; mediana entre sementes; regressão log-log tempo × n (expoente empírico vs. Big-O declarado); comparação só dentro da mesma rota (Python × MATLAB não comparáveis — c122).",
  impl="Sobre o cache de ④ (existe `timing` no notebook §7 para 46/48): adicionar a coluna `tempo_busca_s` à decomposição e a razão busca/fit; figura de barras empilhadas por algoritmo (fit | busca | sonda) — a sonda é custo NOSSO e deve ser descontada (declarar).",
  estado="N — dado pronto (④); custo baixo (extensão de 48).",
  detalhes="Caveats: teto de parede 12 h só na rota Python (615 ⚪ — fichas 29/58 — são exatamente os algoritmos com busca cara: c154, c262, c149, e81); tempos de máquinas diferentes (a torre mediu a dispersão por máquina — ficha 8). Relação: 46, 47, 48, 58. Decisão: descontar a sonda; publicar como painel de 48."),

70: dict(nome="Validação numérica do estimador da aquisição (MC × analítico; aproximações; corretude)", grupo="I",
  fontes="[MIN] 17 análises em 12 artigos (lista abaixo) · [PL-38] R2#20 (2/38) · ficha 30 (sanidade do pipeline).",
  o_que="Checagens de que o número da aquisição está certo: qEHVI MC × EHVI analítico e gradiente amostral × exato (c100), EIHV exato × aproximado (c107), RFF × amostragem exata por dimensão (c131: RFF degrada em alta D), sensibilidade a S/p e às aproximações de entropia JES-0/LB/LB2/MC (c154: 'recomendamos contra a estimativa de variância zero'), |PF| (c214), S (c222: MESMO robusto com S=1, PESMO não), β_t exato do Teorema 1 (c276), POPmin × POPtrue (c65), fórmula fechada × código de referência (e1), Nyström (e81: 'sem perda, ganho leve'), IS/MCS × exato com R² por M (e86: concordância cai com M), proxy de informação × HMC (b15 ρ=0,96).",
  dados="Nenhuma: a instrumentação não grava o valor da aquisição nem uma referência exata. (⑥ grava o ponto escolhido; alguns algoritmos logam o valor — verificar por algoritmo, ficha 78.)",
  objetivo="Nos artigos: garantir que a implementação do critério é correta antes de compará-lo. Na dissertação: não se aplica (usamos implementações publicadas/oficiais — cap. 4 homologação, §D9.5).",
  revela="Que as aproximações baratas costumam bastar (c154, c222, e81) exceto quando M cresce (c154 Marine M=4; e86) ou D cresce (c131) — argumento para o cap. 6.",
  como="Comparação do valor/gradiente do critério calculado de duas formas nos mesmos pontos; dispersão com R²; curvas de desempenho por variante do estimador.",
  tecnicas="Correlação/R² entre estimadores; curvas por variante; teste em problema de brinquedo.",
  impl="Não implementável sem gravar o critério; a homologação (§D9.5) e a ficha 30 são o nosso equivalente.",
  estado="N — não entra.",
  detalhes="Registro para 61/cap. 6 (as aproximações usadas pelos 15 são as dos autores). Relação: 30, 78."),

71: dict(nome="Ilustração didática: o mapa μ/σ do surrogate e a paisagem da aquisição sobre o espaço de decisão (D = 2)", grupo="E",
  fontes="[MIN] 12 análises em 10 artigos (lista abaixo) · [PL-38] R2#17 (3/38) · [CD] ③ regime `sonda` (2.000 pontos Sobol, f verdadeiro em S) · problemas com D = 2 na bateria (MMF1, MMF4).",
  o_que="A figura que mostra, para uma execução e um instante, a média predita, a incerteza e (quando possível) o critério de aquisição sobre todo o espaço — c238 (contornos EI × EIM), emo1 (paisagem do infill com σ fixo), mtm6 (μ, σ e EI_H após 25 iterações), e17 (mapas de calor μ × verdade), c24 (superfície predita × real), e9 e c154 (curvas de nível em brinquedo), c1 (BNN com/sem gradiente em 1D), c241 (exemplo numérico do conflito entre EIs), c29 (localização pelo limiar).",
  dados="③ (regime sonda: μ/σ ou score dos 2.000 pontos, por retreino, `fe_treino_max`); S (f verdadeiro nos mesmos pontos); ① (pontos avaliados até o instante); ⑥ (ponto escolhido).",
  objetivo="Dar ao leitor a intuição do que a sonda mede antes das curvas agregadas (31–34): onde o modelo acerta, onde o σ é grande, onde o algoritmo foi buscar.",
  revela="Se o σ é grande longe dos dados e pequeno perto (comportamento GP), se o classificador acerta a região certa, e se o infill cai onde σ é alto (exploração) ou onde μ é bom (explotação) — a versão visual de 44.",
  como="Para MMF1 e MMF4 (D = 2), 2–3 algoritmos com μ/σ (b3, c238, c262) e 1 com classe (b4/c217): painéis μ, σ, |μ − f| e pontos avaliados, em 3 retreinos (início, meio, fim) da execução mediana; interpolação dos 2.000 pontos Sobol para o mapa.",
  tecnicas="Interpolação/scatter dos pontos da sonda; mapas de calor; execução mediana; sem estatística (é ilustração).",
  impl="Novo bloco no notebook §6 (sonda): filtrar ③ por problema ∈ {MMF1, MMF4}, regime = sonda, e três valores de `fe_treino_max`; juntar com S; `tricontourf`. Uma figura por algoritmo escolhido; o resto no repositório (56).",
  estado="N — dado pronto para os algoritmos com ③ no cache (8) e MMF1/MMF4 (só se a sonda existir para MMF — conferir `data/sonda/`).",
  detalhes="Caveats: MMF são multimodais no espaço de decisão (ficha 25) — a figura mostra isso de graça; só D = 2 é desenhável; a sonda é fixa (não densa como uma grade dedicada). Relação: 31–34, 44, 45. Decisão: quais algoritmos e se entra no corpo ou como abertura do bloco E."),

72: dict(nome="Análise a alvo fixo: avaliações até atingir um nível de IGD+ (ERT / fixed-target), por família", grupo="D",
  fontes="[MIN] 3 análises em 3 artigos (lista abaixo) · ficha 26/27 · convenção COCO/BBOB (a bateria tem 7 funções BBOB) · [CAP4] (as funções BBOB entram via fronts empíricos D72).",
  o_que="Em vez de 'qual IGD+ em 31D−1' (alvo fixo de orçamento), 'quantas avaliações para atingir IGD+ ≤ τ' (alvo fixo de qualidade): b1 mede o múltiplo de avaliações que a busca aleatória precisa para igualar o EGO (2×–250×), c250 conta chamadas até convergência (K-MOGA usa ~50% menos), c29 mede quantas observações o Monte Carlo precisa para igualar o P-algorithm (6× num problema, 2× noutro).",
  dados="① (trajetória de IGD+ por FE, já computada para 26 no cache `trajetorias`); M (alvos por problema: quantis do IGD+ final dos pisos, ou frações fixas).",
  objetivo="Medir eficiência amostral — o que 'expensive' quer dizer — e dar uma leitura robusta às células que não chegaram ao fim (teto de parede: se atingiram o alvo antes, contam).",
  revela="Quantas vezes menos avaliações o assistido precisa para chegar onde o piso chega no fim (e vice-versa onde o piso vence — 16); ERT infinito onde nunca chega (58).",
  como="Para cada célula, o FE em que a trajetória cruza o alvo (alvo = IGD+ final mediano do piso casado, por problema; ou 3 alvos: 2×, 1,5×, 1× do piso); ERT = média das avaliações sobre execuções com sucesso, penalizando insucesso (definição COCO); tabela por família de problema × algoritmo.",
  tecnicas="Fixed-target; ERT (expected running time) com taxa de sucesso; razão ERT_assistido/ERT_piso; mediana entre sementes.",
  impl="Sobre o cache de trajetórias (26): interpolar o primeiro FE com IGD+ ≤ alvo; alvo por problema derivado de 1/9; tabela e uma figura (razão por família). ~1 célula de notebook.",
  estado="N — dado pronto; custo baixo.",
  detalhes="Caveats: o DoE de 11D−1 é comum (contar FE a partir de 0 ou do fim do DoE — declarar); DDMOP7 sem IGD+; alvo derivado do piso é circular se o piso não converge (usar alvo por quantil). Relação: 26, 27, 16, 29, 58. Decisão: definição do alvo."),

73: dict(nome="A recomendação final: ND avaliado (in-sample, ①) × ND acreditado pelo modelo (③) — o custo da convenção de endpoint para métodos informacionais", grupo="E",
  fontes="[MIN] 1 análise (c154 JES, roster: Sec. 5.2 e Apêndice L.5, Fig. 19) · fichas 40/42 (fantasia) · [REG] D70 (endpoint = ND das avaliações reais) · d19.",
  o_que="c154 repete a comparação principal trocando a recomendação: em vez de otimizar a média posterior sobre todo X, restringe-a aos pontos já avaliados X_N — e os métodos informacionais (PES, MES, JES) pioram ('picked points more greedily' favorece os de melhoria/escalarização). A nossa convenção de endpoint (D70) É a versão in-sample.",
  dados="① (ND das avaliações reais — a convenção); ③ (μ nos pontos de busca e da sonda) para reconstruir o ND acreditado; ⑦ no offline (onde a reavaliação já existe).",
  objetivo="Declarar que o placar (1/3/9) mede o que foi AVALIADO, não o que o modelo acredita — e quantificar, para c154/e81/c149, quanto a leitura muda se a recomendação for a 'acreditada' (μ) reavaliada — o que, online, não se pode reavaliar sem experimento; logo, medir a distância |ND acreditado| vs |ND avaliado| (40/42) e argumentar.",
  revela="Se os métodos que exploram (informação/Thompson) são penalizados pela convenção — ressalva obrigatória para não 'decretar vencedor' (d19) — e se o mesmo vale para os pisos (que não têm modelo: a convenção os favorece).",
  como="Parágrafo de método + para c154 e e81: comparar o HV do ND avaliado (①) com o HV do ND 'acreditado' (μ de ③ nos candidatos da última geração; sem reavaliação, portanto HV acreditado, ficha 40) — a diferença mede a fantasia, não o desempenho.",
  tecnicas="Comparação in-sample × recomendação; HV acreditado × HV avaliado; caveat textual.",
  impl="Usa 40 (erro de fantasia) — nada novo além do texto e de um painel para c154/e81.",
  estado="N — parte textual pronta; painel depende de ③ de c154/e81 (decisão 11).",
  detalhes="Vinculante para a leitura de c154/e81/c149 (BO-especiais) no placar; entra no cap. 4 (convenção) ou no cap. 5 (ressalva). Relação: 10, 40, 42, 61."),

74: dict(nome="Robustez a ruído injetado nas avaliações (fora do recorte epistêmico)", grupo="I",
  fontes="[MIN] 6 análises em 5 artigos (lista abaixo) · [PL-38] R2#18 (3/38; R1#11 'não recomendada') · [CAP4] bateria determinística (sem ruído).",
  o_que="Desempenho sob ruído gaussiano injetado: c149 (peso α/β do termo aleatório: sem peso, 93% das amostras vão para o máximo ruidoso), c154 (ParEGO × NParEGO, EHVI × NEHVI: 'ignorar o ruído vai razoavelmente bem'), c262 (controle SEM ruído: qNEHVI não perde quando não há ruído a tratar), e81 (σ² ∈ {0, 1e-6, 1e-4, 1e-3}), b14 (IBEA × NSGA-II sob ruído, sem surrogate).",
  dados="Nenhuma (a bateria é sem ruído). O regime 'noiseless' de c262 corresponde ao nosso — ①.",
  objetivo="Nos artigos: mostrar que a incerteza aleatória modelada protege contra ruído. Na dissertação: fora do recorte (epistêmico); só nota.",
  revela="Que modelar ruído nem sempre paga (c154) e não custa quando não há ruído (c262) — útil para ler qNEHVI (roster) na bateria determinística.",
  como="Níveis de σ² injetado; curvas HV × iteração; contagem de amostras na região ruidosa.",
  tecnicas="Ruído aditivo controlado; curvas por nível.",
  impl="Nenhuma.",
  estado="N — não entra (fora do recorte)."
  , detalhes="Nota em 16/61: c262 é 'noise-aware' rodando sem ruído — o resultado do artigo (Fig. 15) diz que isso não o penaliza. Relação: 61."),

75: dict(nome="Interpretação de engenharia/decisão das soluções não-dominadas nos problemas reais", grupo="C",
  fontes="[MIN] 29 análises em 16 artigos (lista abaixo) · [PL-38] R2#6 (20/38) · ficha 23 (os três reais) · ficha 24 (DDMOP7).",
  o_que="O que as soluções da frente SÃO no domínio: diagramas de tensão (c141 BWBUG), Cp/geometria da asa (e81, c59), campo de escoamento (c91), segmentos da frente × poços/barreiras (e64), custo estrutural de edição (c10), operating point por probabilidade de dominância (c50), status quo dominado (wang4: 'algumas soluções dominam a configuração real vigente'), validação por docking/MD/FEP (c81), envelope operacional (c91), preferência/tolerância do DM (c49), efeito do ponto de referência (c49).",
  dados="① (x e f do ND final por célula); M (semântica das variáveis: RE21 (viga), ESTOQUE40 (política de estoque), DDMOP7 (rede esparsa)); ⑦ no offline.",
  objetivo="Dar aos três reais uma leitura de decisão (o que muda entre as soluções extremas e a do 'joelho') — e, no DDMOP7, dizer que redes a aquisição achou (24).",
  revela="Se as frentes dos assistidos e dos pisos cobrem regiões DIFERENTES do espaço de decisão (não só de objetivos) — e se a incerteza levou a soluções 'estranhas' (fantasia, 40) ou a soluções plausíveis.",
  como="Para cada real: 3 soluções do ND mediano (extremos + joelho) por 2–3 algoritmos, tabela x/f e uma frase de interpretação; comparação com a solução de referência do problema, se houver (RE21 tem front empírico D72; ESTOQUE40 tem política-base?).",
  tecnicas="Seleção de soluções representativas (extremos, joelho por distância à reta); tabela; interpretação de domínio.",
  impl="Célula pequena por real sobre ①; nenhuma métrica nova.",
  estado="N — dado pronto; custo de texto.",
  detalhes="A dissertação é metodológica: recomendo no máximo um parágrafo por caso (23). Relação: 22, 23, 24, 54. Decisão: quais casos ganham interpretação."),

76: dict(nome="Comparação com resultados publicados (fora do protocolo, orçamento não pareado)", grupo="I",
  fontes="[MIN] 3 análises em 3 artigos (b1 vs EANA; jin3 vs Deb & Nain; c10 vs MOEA-RSFMMA no suplemento) · [CAP4] homologação das implementações (§D9.5).",
  o_que="Confrontar o próprio número com o publicado por terceiros no mesmo problema, sem pareamento de orçamento/implementação (b1: 'comparison is difficult').",
  dados="① (endpoint por célula) + números publicados (b3 Table I, b4 Table III, c122, c141, c217, e7, e74 nas mesmas DTLZ/WFG/ZDT).",
  objetivo="Sanidade: as implementações da bateria (oficiais/PlatEMO/BoTorch) reproduzem a ORDEM DE GRANDEZA publicada em DTLZ/ZDT/WFG sob orçamento parecido? (proteção contra bug de configuração).",
  revela="Discrepâncias grosseiras (uma ordem de grandeza) que indicariam erro de implementação ou de régua; nada além disso é interpretável (orçamentos, D, M e réguas diferem).",
  como="Tabela pequena: para 4–6 (algoritmo, problema) com orçamento próximo de 31D−1 nos artigos, IGD publicado × IGD/IGD+ nosso (mesma régua, se possível); comentário.",
  tecnicas="Comparação descritiva; sem teste.",
  impl="Manual (ler tabelas dos artigos); uma tarde.",
  estado="N — não recomendada como análise; como sanidade do cap. 4 (homologação), opcional.",
  detalhes="Relação: 61, §D9.5. Cuidado com N15 (nenhum número de b15)."),

77: dict(nome="O peso do sorteio inicial: qualidade do DoE (11D−1) × endpoint, por semente", grupo="A",
  fontes="[MIN] 3 análises em 3 artigos (e103 LHS × aleatória 'pouco efeito'; e3 tamanho do DoE 'sem diferença significativa'; e8 qualidade do clustering inicial) · ficha 8 (dispersão entre sementes) · [CAP4] DoE compartilhado por semente (D25).",
  o_que="Quanto do resultado final é o sorteio: correlação, por célula, entre a qualidade do DoE (IGD+/HV do ND do DoE, igual para todos os algoritmos na mesma semente) e o endpoint; e quanto da variância entre sementes (8) é explicada pelo DoE.",
  dados="① (fase = DoE vs infill; fe_index ≤ 11D−1); C (endpoint por semente).",
  objetivo="Justificar o pareamento por semente (5/9) e medir se algoritmos 'gulosos' dependem mais do ponto de partida que os exploratórios (a incerteza como seguro contra um DoE ruim).",
  revela="Se a ordem entre algoritmos muda com a qualidade do sorteio (interação DoE × algoritmo) — e se o piso é mais sensível ao DoE que o assistido (ou o contrário).",
  como="Por célula: IGD+ do DoE e IGD+ final; Spearman entre os dois sobre as 30 sementes, por (algoritmo, problema); fração da variância do endpoint explicada pelo DoE (R² de regressão simples); figura: Δ(final − DoE) × qualidade do DoE por família de algoritmo.",
  tecnicas="Correlação de Spearman; R²; boxplots pareados.",
  impl="Sobre o cache de endpoint + um cálculo do ND do DoE por semente (① filtrado por fase) — uma célula.",
  estado="N — dado pronto; custo baixo.",
  detalhes="Relação: 5, 8, 9, 14 (versão offline: o dataset é o DoE). Nenhum artigo do corpus mede isso — leitura própria e barata."),

78: dict(nome="O decaimento do valor da aquisição ao longo do orçamento (o modelo acha que ainda há o que ganhar?)", grupo="E",
  fontes="[MIN] 1 análise (e8 Fig. S11: KDE de E[I] e P[I] por geração) · fichas 43/45 · [CD] ⑥ (campos por evento — verificar se há `acq_value`).",
  o_que="A distribuição do valor do critério (EI/EHVI/UCB/entropia) nos pontos escolhidos, geração a geração — tende a zero quando o modelo 'acha' que convergiu (ou quando o σ colapsa: 35 'degenera').",
  dados="⑥ (se o evento de escolha grava o valor do critério) ou ③ (μ/σ do escolhido → recomputar EI para os GP simples: b1, b3, c238).",
  objetivo="Ler a auto-avaliação do algoritmo (quanto ele espera melhorar) contra a melhoria real (43): descolamento = fantasia (40) ou σ degenerado (35).",
  revela="Se os algoritmos param de 'esperar ganho' antes de parar de ganhar (σ degenerado) ou depois (fantasia).",
  como="Curva do valor mediano do critério por geração × Δ IGD+ real por geração; por algoritmo com critério explícito.",
  tecnicas="Séries por geração; correlação defasada.",
  impl="Depende do parser do ⑥ (45); se o valor não estiver gravado, recomputar EI de μ/σ (③) só para GP com EI/UCB fechados.",
  estado="N — verificar disponibilidade no ⑥; senão cair.",
  detalhes="Relação: 35, 40, 43, 45. Decisão: só se 45 for feita."),

79: dict(nome="O front por nível de confiança — filtrar o ND acreditado pelo σ e reavaliar (regime offline)", grupo="B",
  fontes="[MIN] 4 análises em 2 artigos (c49: preferência + tolerância de incerteza do DM sobre 1,96σ; c97: fronteiras por confiabilidade 0,99/0,8/0,66/0,5 e por tamanho do ensemble) · fichas 13/14/42 · [CD] ③ + ⑦.",
  o_que="No offline, a incerteza é a única defesa contra o modelo: o front 'acreditado' filtrado por quantil de σ (só soluções com σ baixo) e reavaliado na verdade (⑦) — c97 mostra que ensembles pequenos subestimam σ e produzem fronteiras 'aparentemente melhores' mas infactíveis; c49 aplica tolerâncias do DM e fica com poucas soluções.",
  dados="③ (σ das soluções do ND final, regime busca) para b5 (Prob-RVEA/MOEA/D) e e103; ⑦ (reavaliação); ① (dataset).",
  objetivo="Mostrar se o σ do modelo offline separa as soluções que sobrevivem à reavaliação das que não sobrevivem — a versão 'de decisão' de 33/34 no offline.",
  revela="Se 'confiar menos' (filtrar por σ) compra fidelidade ao custo de cobertura: HV reavaliado × nível de confiança; e se o b5m (que usa σ na seleção) chega a um ND mais confiável que o moead_media (11).",
  como="Para cada célula offline: ordenar o ND final por σ (médio entre objetivos — ver 37); para quantis 100/75/50/25%: HV acreditado (μ) e HV reavaliado (⑦) do subconjunto; curva HV_real × quantil, com o moead_media como controle (sem σ).",
  tecnicas="Filtragem por quantil de σ; HV com referência D69; curva por confiança; comparação pareada por semente.",
  impl="Sobre ③ + ⑦ das 5 configs offline (b5m, b5r, e103, treed_media?, moead_media): join por solution_id; ~1 célula.",
  estado="N — dado pronto se ③ do offline gravar σ por solução do ND (conferir); custo baixo.",
  detalhes="Relação: 11, 13, 14, 33, 42. Caveat: e103 (IBEA-MS) usa classe/ordem, não σ contínuo — só b5 e treed. Decisão: entra no bloco offline como figura."),

80: dict(nome="Correlação entre objetivos nos problemas da bateria (característica do problema)", grupo="C",
  fontes="[MIN] 1 análise (c81 Table C.1: |ρ| < 0,3 justifica a agregação multiplicativa) + c82 (ficha 17: correlação controlável muda a vantagem) + b15/c106 (68: modelar a correlação não ajuda) · ficha 17 (matriz de características D98) · ficha 37.",
  o_que="A correlação (Pearson/Spearman) entre os objetivos sobre o espaço amostrado (DoE) e sobre o front de referência, por problema — uma coluna da matriz de características, que explica quando 'm sigmas independentes' são um problema (37) e quando escalarizações (b1, b3) sofrem.",
  dados="① (f do DoE, comum a todos por semente) ou S (gabarito da sonda: 2.000 pontos com f); M (fronts de referência).",
  objetivo="Completar a matriz de características (D98) com uma medida contínua e reproduzível, e testar se a correlação prediz a vantagem das classes de função (17/20).",
  revela="Se problemas com objetivos anticorrelacionados (conflito forte) favorecem métodos de hipervolume/informação e os correlacionados favorecem escalarização — hipótese de c82.",
  como="Por problema: matriz de correlação dos objetivos nos 2.000 pontos Sobol (S) e no front de referência; escalar (ρ médio); coluna na tabela de características; cruzamento com 17.",
  tecnicas="Pearson/Spearman; tabela.",
  impl="Sobre S (`data/sonda/sonda_{problema}.parquet`) — trivial; DDMOP7 sem sonda (usar ①).",
  estado="N — dado pronto; custo mínimo.",
  detalhes="Relação: 17, 18, 20, 37. Decisão: entra como coluna, não como seção."),

81: dict(nome="Sensibilidade do placar ao ponto de referência do HV e à normalização (régua)", grupo="I",
  fontes="[MIN] 2 análises em 2 artigos (c261: z* da decomposição — 'pouco sensível, exceto ZDT1–3 e DTLZ7'; e86: método de Ishibuchi para o ponto de referência — 'sem melhora evidente') · fichas 61/62 (avisos de régua; ideais arredondados A53) · [REG] D69 (referência 1,1), S.5 (ideal/nadir).",
  o_que="Se as conclusões do placar (1/3/9) mudam quando a referência do HV vai de 1,1 para 1,2 ou para a regra de Ishibuchi (1 + 1/H), e quando a normalização usa os ideais exatos em vez dos arredondados (ZDT6/MMF4/MMF1 — A53).",
  dados="① (ND por célula — recomputar HV); M (réguas `F_MIN_MAX`; ideais alternativos).",
  objetivo="Robustez de régua: mostrar que o veredito não depende da convenção (ou onde depende).",
  revela="Problemas em que o ranking inverte com a referência (frentes com extremos longos — DTLZ7, WFG desconexos) e o efeito dos ideais arredondados.",
  como="Recomputar HV para 3 referências × 2 réguas; comparar rank médio (2) e símbolos (3) entre variantes; tabela de concordância (Kendall τ entre rankings).",
  tecnicas="Recomputação de HV; Kendall τ; tabela de inversões.",
  impl="`metrics.metrics_of_set` com `reference_bounds` alternativos — uma célula; custo de cômputo (HV para 16.020 células × 6 variantes) moderado.",
  estado="N — dado pronto.",
  detalhes="Relação: 1, 2, 3, 61, 62; decisão 8 (ideais arredondados: manter declarando × recomputar — esta ficha responde 'quanto muda')."),
}
GRUPO_TITULO = {"A":"Grupo A","B":"Grupo B","C":"Grupo C","D":"Grupo D","E":"Grupo E","F":"Grupo F","G":"Grupo G","H":"Grupo H","I":"Grupo I","J":"Grupo J"}
